### ISSUE TITLE
Treesitter errors "W18: Invalid character in group name" "Unable to parse"

### ISSUE THREAD

**Issue by jwbaldwin** [nvim-neorg/neorg#559]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.8.0-dev-922-g42e9fe7d9

### Neorg setup
```
# custom.p.neorg.lua
local neorg = require("neorg")

neorg.setup {
  load = {
    ["core.defaults"] = {},
    ["core.gtd.base"] = {
      config = {
        workspace = "project"
      }
    },
    ["core.norg.concealer"] = {
    },
    ["core.norg.completion"] = {
      config = {
        engine = "nvim-cmp"
      }
    },
    ["core.norg.dirman"] = {
      config = {
        workspaces = {
          project = "~/neorg/project",
        }
      }
    }
  }
}

#nvchad install of plugins see https://nvchad.com/config/plugins
  ["nvim-neorg/neorg"] = {
    after = "nvim-treesitter",
    config = function()
      require "custom.p.neorg"
    end
  },
```

### Actual behavior

1. Start up Neovim
2. run `:NeorgStart`
3. Get the following error:
```
W18: Invalid character in group name
W18: Invalid character in group name
```
4. Press escape to continue to empty index.norg
5. Try to edit and recieve the following error:
```
...ua/neorg/modules/core/integrations/treesitter/module.lua:503
Unable to parse the current document's syntax tree :(
```
6. If I run `:Neorg inejct-metadata` the error from 5. never appears again unless I leave the `.norg` file and try something like `:Neorg gtd views`

Other information:
- Packer install contains `after = "nvim-treesitter"`
- No syntax highlighting happens on the document EXCEPT code snippets work
- `:highlight` doesn't show any Neorg group
- output from `:checkhealth nvim-treesitter` looks good:
```
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: tree-sitter found 0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: node found v18.7.0 (only needed for :TSInstallFromGrammar)
  - OK: git executable found.
  - OK: cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - norg_meta      ✓ . . ✓ .
  - eex            ✓ . . . ✓
  - heex           ✓ ✓ ✓ ✓ ✓
  - norg           ✓ . ✓ . ✓
  - css            ✓ . ✓ ✓ ✓
  - elixir         ✓ ✓ ✓ ✓ ✓
  - erlang         ✓ . ✓ . .
  - c              ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Expected behavior

I expect the .norg file to not throw errors on open and to highlight.

### Steps to reproduce

An empty norg file seems to work. This is a fresh install.

### Help

No

**Comment by vhyrro** [comment]
Yup, @Jan9103 is correct. `0.0.13` introduces a breaking change to highlights. This is because there was a breaking change in Treesitter highlighting and I adapted to it. To use the latest Neorg version you also have to be on the latest Neovim nightly, sorry. You can still use `0.0.12` on older versions just fine though :)

**Comment by vhyrro** [comment]
Are you certain? Here are some things I'd try:
- Remove your packer folder and reinstall all plugins (errors in treesitter can stall packer and prevent it from properly updating things)
- Make sure that the nightly you may be using from e.g. your package manager is actually the latest nightly, not some older version of it.

If both of those fail could you give me the output of `nvim --version`? Cause a bunch of people have told me that updating to the latest nightly fixed it for them :thinking:

**Comment by gsuuon** [comment]
I wiped pack/packer and did a clean install, still running into
```
...ua/neorg/modules/core/integrations/treesitter/module.lua:503
Unable to parse the current document's syntax tree :(
```
On windows 10, `:version`:
NVIM v0.8.0-dev-973-g253f0ffd8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az171-465

**Comment by vhyrro** [comment]
@gsuuon do the "Invalid character in group name" errors still persist? Or is it just the "Unable to parse current document's syntax tree" error?

**Comment by gsuuon** [comment]
I only see "Unable to parse current document's syntax tree"

**Comment by vhyrro** [comment]
Okay I see then something else must've broken in the process, rip. Could you send me your Neorg config please?

**Comment by gsuuon** [comment]
```
    use {
        "nvim-neorg/neorg",
        config = function()
            require('neorg').setup {
                load = {
                    ['core.defaults'] = {},
                    ['core.norg.journal'] = {
                        config = {
                            strategy = 'flat'
                        }
                    },
                    ['core.norg.dirman'] = {
                        config = {
                            workspaces = {
                                notes = '~/notes/',
                            }
                        }
                    },
                    ['core.gtd.base'] = {
                        config = {
                            workspace = 'notes'
                        }
                    },
                }
            }
        end,
        requires = "nvim-lua/plenary.nvim"
    }
```
I also tried adding `after='nvim-treesitter'` and saw the same thing

**Comment by oncomouse** [comment]
FWIW, I'm getting the same error as @gsuuon, but only when I open blank `.norg` files.

**Comment by vhyrro** [comment]
Thanks for the heads up! I didn't get time to debug that yesterday. I'll let you guys know when i figure out a fix (might take a few hrs so hang on tight)

**Comment by vhyrro** [comment]
Alright, this hopefully should be fixed now, but it may take a while before the fix propagates to all users.

The error was in treesitter, it treated empty Neorg documents as an error. Now all we have to do is wait for `nvim-treesitter` to update their lockfiles (which i believe happens every 4 hours?). Try `:TSUpdate`-ing every now and again!

**Comment by jwbaldwin** [comment]
@vhyrro Awesome! Most recent update worked for me and resolved the issue! Thank you for this, I hope I can contribute in the future :)

**Comment by gsuuon** [comment]
Fixed for me as well, thank you!

**Comment by SteveWolligandt** [comment]
Unfortunately I am still getting the following error:
```
W18: Invalid character in group name
Error executing vim.schedule lua callback: ...start\neorg/lua/neorg/modules/core/highlights/module.lua:571: Expected lua string
stack traceback:
        [C]: in function 'cmd'
        ...start\neorg/lua/neorg/modules/core/highlights/module.lua:571: in function 'callback'
        ...start\neorg/lua/neorg/modules/core/highlights/module.lua:528: in function 'descend'
        ...start\neorg/lua/neorg/modules/core/highlights/module.lua:529: in function 'descend'
        ...start\neorg/lua/neorg/modules/core/highlights/module.lua:535: in function 'trigger_highlights'
        ...start\neorg/lua/neorg/modules/core/highlights/module.lua:691: in function 'on_event'
        ...m-data\site\pack\packer\start\neorg/lua/neorg/events.lua:153: in function <...m-data\site\pack\packer\start\neorg/lua/neorg/events.lua:140>
```
No matter if I open a file or start neovim without a file.

Additionally there is no NeorgStart command available anymore. After starting neovim I can directly use Neorg <command>

I did a fresh install of Packer and this is my config:
```
use {
   "nvim-neorg/neorg",
   config = function()
     require('neorg').setup {
       load = {
         ["core.norg.dirman"] = {
           config = {
             workspaces = {
               uni = "~\\notes\\uni",
               home = "~\\notes\\home",
             }
           }
         },
         ["core.norg.concealer"] = {config = {}},
       }
     }
   end,
   requires = {
     "nvim-lua/plenary.nvim",
   }
 }
```
This is my treesitter config
```
local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()
 require('nvim-treesitter.configs').setup {
   ensure_installed = { "norg", "haskell", "cpp", "c", "javascript", "markdown" },
   highlight = { -- Be sure to enable highlights if you haven't!
     enable = true,
   }
 }
```

I am on Windows and `nvim --version` says
```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az276-503

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by vhyrro** [comment]
@SteveWolligandt Your issue is that you're on Neovim `0.7.2`, whereas it needs to be the latest nightly.

If you can't (or don't want to) use the nightly version of Neovim then I recommend putting `tag = "0.0.12"` in your `use` declaration for Neorg and use that older version (the breaking change was introduced in `0.0.13`, hence the version change :p).

**Comment by vhyrro** [comment]
The fact that Neorg is starting instantly is... weird. I can observe the same behaviour too. There was a recent PR to add a `lazy_loading` option. Perhaps there's a logic bug that's autoloading Neorg every time.

**Comment by SteveWolligandt** [comment]
I tried updating and now everything works perfectly. Thanks for your quick reply!
The automatic loading of Neorg still appears.

**Comment by vhyrro** [comment]
Since this issue is pinned and resolved I think it's safe to close :)

**Comment by mkastner** [comment]
`W18: Invalid character in group name` 

Getting this error since this morning's update. All was fine on yesterday's update.

Running macos, nvim nightly, vim-plug, and latest rev 0.0.14

The error disappears when commenting out all entries in the load the load section

```
require('neorg').setup {
    load = {
--        ['core.defaults'] = {},
--        ['core.norg.dirman'] = {
--            config = {
--                workspaces = {
--                    work = '~/notes/work',
--                    home = '~/notes/home',
--                }
--            }
--        },
--        ['core.norg.concealer'] = {}
    }
}
```

**Comment by max397574** [comment]
which neovim version do you have? -> how old is your nightly?

**Comment by mkastner** [comment]
Sorry, I forgot to mention that. It's from this morning (CET):

NVIM v0.8.0-dev+476-g3a4fa22ba

I also happens on the latest homebrew release version: 

NVIM v0.7.2

**Comment by max397574** [comment]
I think it's expected to happen on 0.7.2 since there was a change with highlight group names
but it shouldn't happen with latest dev 🤔

**Comment by mkastner** [comment]
@max397574 

Thanks for your reply. Maybe, it's just me or my config or something else on my side of the fence. If I remain the only one running into this problem, then most likely it _is_ me or my config.
